"""Constants for TimeFlowCodec."""

PLANE_R = 0
PLANE_G = 1
PLANE_B = 2
PLANE_Y = 0
PLANE_U = 1
PLANE_V = 2

MODE_TFC_LINEAR = 0
MODE_TFC_CONST = 1
MODE_FB_RAW = 2
MODE_TFC_MATRIX = 3
MODE_RESERVED = MODE_TFC_MATRIX

DEFAULT_TAU = 0.1
DEFAULT_SLOPE_THRESHOLD = 1e-3
COLOR_FORMAT_RGB = 1
COLOR_FORMAT_YUV444 = 2
COLOR_FORMAT_YUV420 = 3
BITS_PER_MODE = 2

COMP_NONE = 0
COMP_ZLIB = 1
COMP_LZMA = 2
COMP_ZSTD = 3
