"""Constants for RGB TimeFlowCodec."""

PLANE_R = 0
PLANE_G = 1
PLANE_B = 2

MODE_TFC_LINEAR = 0
MODE_TFC_CONST = 1
MODE_FB_RAW = 2
MODE_RESERVED = 3

DEFAULT_TAU = 0.1
DEFAULT_SLOPE_THRESHOLD = 1e-3
COLOR_FORMAT_RGB = 1
BITS_PER_MODE = 2
